# render.yaml
services:
  - type: web_service        # Docker‐basiert
    name: transkript-tool    # Dein Service‐Name bei Render
    env: docker              # zwingt auf Docker‐Environment
    branch: main             # Branch, den Render deployen soll
    dockerfilePath: Dockerfile
    buildContext: .
    containerPort: 10000     # <<< hier sagst Du Render, auf Port 10000 zu pingen
    autoDeploy: true
